#version 450
#extension GL_ARB_separate_shader_objects : enable

#define WORKGROUP_SIZE 32

layout (local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE, local_size_z = 1 ) in;

layout(binding = 0) uniform OutputData {
    uint width;
    uint height;
	uint depth;
};

layout(std140, binding = 1) buffer Output0 {
    vec4 outputBuffer[];
};

void main() {
	uint id = width * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x;
	float r = float(gl_LocalInvocationID.x) / 32.0 ;
	float g = 1 - float(gl_LocalInvocationID.y) / 32.0;
	float b = float(gl_LocalInvocationID.y) / 32.0;
	outputBuffer[id] = vec4(r, g, b, 1.0);
}